name: code-quality
on: [push]
jobs:
  build:

    runs-on: [ ubuntu-latest ]
    steps:
      - name: Install Linux specific
        run: |
              sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0
        shell: bash
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      - name: ovpn3-connect-action-container
        uses: maxmazzeschi/ovpn3-connect-action@main
        with:
          ovpn-config:  ${{ secrets.OVPN_CONFIG }}
          vpn-user:     ${{ secrets.OVPN_USER }}
          vpn-pass:     ${{ secrets.OVPN_PASS }}   
      - uses: sonarsource/sonarqube-scan-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Kill VPN Connection
        if: always()
        run: |
          sudo pkill openvpn
          